### Create a new user
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1996,
  "mileage": 100000,
  "price": 500000,
  "lng": 0,
  "lat": 0
}